export const GET_CITY_INFO = 'GET_CITY_INFO';
export const GET_POSITION = 'GET_POSITION';
export const UPATE_MERCHANT_FORM_DATA = 'UPATE_MERCHANT_FORM_DATA';
export const CLEAR_AND_UPATE_MERCHANT_FORM_DATA = 'CLEAR_AND_UPATE_MERCHANT_FORM_DATA';